//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace meli_challenge_dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personas:IPersonas
    {
        public long PersonaId { get; set; }
        public string DNA { get; set; }
        public int ArrayLenght { get; set; }
        public Nullable<bool> IsMutant { get; set; }
    }

    public interface IPersonas
    {
        long PersonaId { get; set; }
        string DNA { get; set; }
        int ArrayLenght { get; set; }
        Nullable<bool> IsMutant { get; set; }
    }
}
